#kubectl version  
# for deploy go to the k8s root and enter kubectl apply -f platforms-depl.yaml
# deploy olduktan sonra deployment.apps/platforms-depl created diyor
# kubectl get deployments
# kubectl get pods
# kubectl delete deployments platforms-depl yaparsan ucurur
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels: 
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: 1171602003/platformservice:latest
